title: Alexandre Lima
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme
